#!/bin/sh

if [ "$PATH_INFO" = "/assets/goldblum.jpg" ]; then
	echo "Content-type: image/jpeg"
	echo
	cat goldblum.jpg
else
	echo "404 Not found"
	echo
	echo "Go somewhere else to find $PATH_INFO"
fi
