#!/bin/sh

echo "Content-type: text/html"
echo
cat <<dog
<title>Goldblum</title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<style type="text/css">
body {
	margin: 0;
	background: black;
	color: white;
}

.wrapper, .upper, .bottom {
	position: absolute;
	width: 100%;
}

.wrapper {
	height: 100%;
	text-align: center;
}

.upper {
	background-image: url("assets/goldblum.jpg");
	background-position: center center;
	background-repeat: no-repeat;
	background-size: contain;
	top: 0;
	bottom: 4em;
}

.bottom {
	bottom: 0;
	height: 4em;
}

h1 {
	font-size: 2em;
}


</style>
<div class="wrapper">
	<div class="upper">
	</div>
	<div class="bottom">
		<h1>Request Handled by: $HOSTNAME</h1>
	</div>
</div>
dog
