#!/bin/sh

echo "Content-type: text/html"
echo
cat <<dog
<title>Goldblum</title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<style type="text/css">
body {
	margin: 0;
	background: black;
}
img {
	width: 100%;
	height: 100%;
	object-fit: contain;
}
h1 {
	color: white;
}
</style>
<div style="width: 100%; height: 100%; text-align: center">
<img src="assets/goldblum.jpg" />
<h1>$HOSTNAME</h1>
</div>
dog
